/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BentoAbi",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BentoAbi__factory>;
    getContractFactory(
      name: "CauldronAbi",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CauldronAbi__factory>;
    getContractFactory(
      name: "MimAbi",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MimAbi__factory>;
    getContractFactory(
      name: "ShibAbi",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ShibAbi__factory>;
    getContractFactory(
      name: "SwapperAbi",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SwapperAbi__factory>;

    getContractAt(
      name: "BentoAbi",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BentoAbi>;
    getContractAt(
      name: "CauldronAbi",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CauldronAbi>;
    getContractAt(
      name: "MimAbi",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MimAbi>;
    getContractAt(
      name: "ShibAbi",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ShibAbi>;
    getContractAt(
      name: "SwapperAbi",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SwapperAbi>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
