/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface SwapperAbiInterface extends utils.Interface {
  functions: {
    "bentoBox()": FunctionFragment;
    "factory()": FunctionFragment;
    "pairCodeHash()": FunctionFragment;
    "swap(address,address,address,uint256,uint256)": FunctionFragment;
    "swapExact(address,address,address,address,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bentoBox"
      | "factory"
      | "pairCodeHash"
      | "swap"
      | "swapExact"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "bentoBox", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pairCodeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapExact",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "bentoBox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pairCodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapExact", data: BytesLike): Result;

  events: {};
}

export interface SwapperAbi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SwapperAbiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bentoBox(overrides?: CallOverrides): Promise<[string]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    pairCodeHash(overrides?: CallOverrides): Promise<[string]>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      shareToMin: PromiseOrValue<BigNumberish>,
      shareFrom: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapExact(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      refundTo: PromiseOrValue<string>,
      shareFromSupplied: PromiseOrValue<BigNumberish>,
      shareToExact: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  bentoBox(overrides?: CallOverrides): Promise<string>;

  factory(overrides?: CallOverrides): Promise<string>;

  pairCodeHash(overrides?: CallOverrides): Promise<string>;

  swap(
    fromToken: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    shareToMin: PromiseOrValue<BigNumberish>,
    shareFrom: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapExact(
    fromToken: PromiseOrValue<string>,
    toToken: PromiseOrValue<string>,
    recipient: PromiseOrValue<string>,
    refundTo: PromiseOrValue<string>,
    shareFromSupplied: PromiseOrValue<BigNumberish>,
    shareToExact: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bentoBox(overrides?: CallOverrides): Promise<string>;

    factory(overrides?: CallOverrides): Promise<string>;

    pairCodeHash(overrides?: CallOverrides): Promise<string>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      shareToMin: PromiseOrValue<BigNumberish>,
      shareFrom: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        extraShare: BigNumber;
        shareReturned: BigNumber;
      }
    >;

    swapExact(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      refundTo: PromiseOrValue<string>,
      shareFromSupplied: PromiseOrValue<BigNumberish>,
      shareToExact: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        shareUsed: BigNumber;
        shareReturned: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    bentoBox(overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    pairCodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      shareToMin: PromiseOrValue<BigNumberish>,
      shareFrom: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapExact(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      refundTo: PromiseOrValue<string>,
      shareFromSupplied: PromiseOrValue<BigNumberish>,
      shareToExact: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bentoBox(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pairCodeHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swap(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      shareToMin: PromiseOrValue<BigNumberish>,
      shareFrom: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapExact(
      fromToken: PromiseOrValue<string>,
      toToken: PromiseOrValue<string>,
      recipient: PromiseOrValue<string>,
      refundTo: PromiseOrValue<string>,
      shareFromSupplied: PromiseOrValue<BigNumberish>,
      shareToExact: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
